export const theme = {
  fonts: {
    mono: "'Share Tech Mono', monospace",
    body: "'Barlow Condensed', sans-serif",
  },
  colors: {
    bg:         "#060a0f",
    surface:    "rgba(15,23,42,0.8)",
    green:      "#10b981",
    greenDim:   "rgba(16,185,129,0.15)",
    greenBorder:"rgba(16,185,129,0.3)",
    red:        "#f87171",
    redDim:     "rgba(239,68,68,0.1)",
    redBorder:  "rgba(239,68,68,0.3)",
    text:       "#e2e8f0",
    textMuted:  "#94a3b8",
    textDim:    "#475569",
    border:     "rgba(16,185,129,0.15)",
    rowBorder:  "rgba(30,41,59,0.8)",
  },
}
 
export const globalStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Barlow+Condensed:wght@400;600;700&display=swap');
  * { box-sizing: border-box; }
  @keyframes fadeIn   { from { opacity:0; transform:translateY(8px); } to { opacity:1; transform:none; } }
  @keyframes scanline { 0% { transform:translateY(-100%); } 100% { transform:translateY(100vh); } }
  @keyframes pulse    { 0%,100% { opacity:1; } 50% { opacity:0.4; } }
  @keyframes blink    { 0%,49%,100% { opacity:1; } 50% { opacity:0; } }
  tr { animation: fadeIn 0.3s ease both; }
  select option { background: #0f172a; color: #e2e8f0; }
  input:focus, select:focus { border-color: #10b981 !important; }
`
 
export const sharedStyles = {
  root: {
    minHeight: "100vh",
    background: "#060a0f",
    backgroundImage: `
      radial-gradient(ellipse at 20% 50%, rgba(16,185,129,0.04) 0%, transparent 60%),
      radial-gradient(ellipse at 80% 20%, rgba(239,68,68,0.04) 0%, transparent 50%)
    `,
    fontFamily: theme.fonts.body,
    color: "#cbd5e1",
    position: "relative" as const,
    overflow: "hidden",
  },
  noise: {
    position: "fixed" as const,
    inset: 0,
    backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E")`,
    pointerEvents: "none" as const,
    zIndex: 0,
  },
  scanline: {
    position: "fixed" as const,
    top: 0, left: 0, right: 0,
    height: "2px",
    background: "linear-gradient(transparent, rgba(16,185,129,0.15), transparent)",
    animation: "scanline 8s linear infinite",
    pointerEvents: "none" as const,
    zIndex: 1,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 32px",
    borderBottom: "1px solid rgba(16,185,129,0.2)",
    background: "rgba(6,10,15,0.9)",
    backdropFilter: "blur(8px)",
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
  },
  headerTitle: {
    fontFamily: theme.fonts.mono,
    fontSize: 20,
    color: theme.colors.green,
    letterSpacing: 4,
  },
  headerSub: {
    fontSize: 12,
    color: theme.colors.textDim,
    letterSpacing: 2,
    marginTop: 2,
  },
  logoutBtn: {
    fontFamily: theme.fonts.mono,
    fontSize: 12,
    color: theme.colors.red,
    background: "transparent",
    border: `1px solid ${theme.colors.redBorder}`,
    padding: "8px 16px",
    cursor: "pointer",
    letterSpacing: 2,
  },
  main: {
    padding: "24px 32px",
    position: "relative" as const,
    zIndex: 2,
  },
  sectionTitle: {
    fontFamily: theme.fonts.mono,
    fontSize: 14,
    color: theme.colors.green,
    letterSpacing: 3,
  },
  actionBtn: {
    fontFamily: theme.fonts.mono,
    fontSize: 12,
    color: theme.colors.green,
    background: theme.colors.greenDim,
    border: `1px solid ${theme.colors.greenBorder}`,
    padding: "8px 20px",
    cursor: "pointer",
    letterSpacing: 2,
  },
  tableWrap: {
    border: `1px solid ${theme.colors.border}`,
    background: "rgba(15,23,42,0.6)",
    overflowX: "auto" as const,
  },
  th: {
    padding: "10px 16px",
    textAlign: "left" as const,
    fontSize: 11,
    letterSpacing: 3,
    color: theme.colors.green,
    borderBottom: `1px solid rgba(16,185,129,0.2)`,
    fontFamily: theme.fonts.mono,
    background: "rgba(16,185,129,0.05)",
  },
  td: {
    padding: "12px 16px",
    fontSize: 14,
    color: theme.colors.textMuted,
    verticalAlign: "middle" as const,
    borderBottom: `1px solid ${theme.colors.rowBorder}`,
  },
  select: {
    background: "rgba(15,23,42,0.9)",
    border: "1px solid rgba(51,65,85,0.6)",
    color: "#94a3b8",
    padding: "4px 8px",
    fontSize: 12,
    fontFamily: theme.fonts.mono,
    cursor: "pointer",
    outline: "none",
  },
  input: {
    background: "rgba(15,23,42,0.9)",
    border: "1px solid rgba(51,65,85,0.6)",
    color: "#e2e8f0",
    padding: "10px 14px",
    fontSize: 14,
    fontFamily: theme.fonts.body,
    outline: "none",
    width: "100%",
  },
  label: {
    fontSize: 11,
    letterSpacing: 3,
    color: theme.colors.textDim,
    fontFamily: theme.fonts.mono,
  },
  errorBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: theme.colors.redDim,
    border: `1px solid ${theme.colors.redBorder}`,
    color: theme.colors.red,
    padding: "10px 16px",
    marginBottom: 16,
    fontSize: 14,
    fontFamily: theme.fonts.mono,
  },
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    backdropFilter: "blur(4px)",
  },
  modal: {
    background: "#0a1220",
    border: "1px solid rgba(16,185,129,0.3)",
    width: "100%",
    maxWidth: 480,
    animation: "fadeIn 0.2s ease",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 24px",
    borderBottom: "1px solid rgba(16,185,129,0.2)",
    background: "rgba(16,185,129,0.05)",
  },
  modalTitle: {
    fontFamily: theme.fonts.mono,
    fontSize: 14,
    color: theme.colors.green,
    letterSpacing: 3,
  },
  modalClose: {
    background: "none",
    border: "none",
    color: theme.colors.textDim,
    cursor: "pointer",
    fontSize: 16,
  },
  submitBtn: {
    fontFamily: theme.fonts.mono,
    fontSize: 13,
    color: theme.colors.green,
    background: theme.colors.greenDim,
    border: `1px solid ${theme.colors.greenBorder}`,
    padding: "12px",
    cursor: "pointer",
    letterSpacing: 2,
    width: "100%",
    marginTop: 8,
  },
}